### ISSUE TITLE
Encoding is necessary?

### ISSUE THREAD

**Issue by shuto-S** [shuto-S/python3-gearman#1]
https://github.com/shuto-S/py3gearman/blob/master/py3gearman/connection.py#L189

**Comment by dorogoy** [comment]
Yes, it is, please have a look to my PR #2

**Comment by dorogoy** [comment]
It seems this only affect admin tasks. Forget my PR ...

**Comment by shuto-S** [comment]
@dorogoy Don't worry.
I also do not know well.

**Comment by shuto-S** [comment]
add test/admin_client.py

Affect on admin client this issue.
Should we separate processing between the admin client and others?

**Comment by shuto-S** [comment]
fix
c6e9baf03d0db142ee2a3e9a7fd41bc9943be5ed
