### ISSUE TITLE
GearmanAdminClient.get_workers() does not work

### ISSUE THREAD

**Issue by agronick** [shuto-S/python3-gearman#3]
GearmanAdminClient.get_workers()  fails with 

line 191, in send_commands_to_buffer
```
    packed_data += packed_command
TypeError: can't concat str to bytearray
```

This monkey patch fixes it:
```
broke_function = gearman.protocol.pack_text_command
def pack_text_command(*args, **kwargs):
    return broke_function(*args, **kwargs).encode('ascii')
gearman.connection.pack_text_command = pack_text_command
```

Put `.encode('ascii')` on `pack_text_command` and it will fix this issue.

**Comment by shuto-S** [comment]
Tanks, issue.
It is the same problem as this issue #1 
I fixed in v0.2.0.
c6e9baf03d0db142ee2a3e9a7fd41bc9943be5ed
